# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [21]
    runs-on: ubuntu-22.04
    #permissions:
    #  contents: read
    #  packages: write

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: validate gradle wrapper
      uses: gradle/wrapper-validation-action@v2
    - name: setup jdk ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'microsoft'
    - name: make gradle wrapper executable
      run: chmod +x ./gradlew
    - name: build
      run: ./gradlew build
    - name: capture build artifacts
      if: ${{ matrix.java == '21' }} # Only upload artifacts built from latest java
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: build/libs/

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    #- name: Publish to GitHub Packages
    #  run: ./gradlew publish
    #  env:
    #    USERNAME: ${{ github.actor }}
    #    TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # 
    - name: Publish to Modrinth
      run: ./gradlew modrinth
      env:
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
