
name: Gradle Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  modrinth_publish:
    uses: ./.github/workflows/build.yml
    steps:
    - name: Publish to Modrinth
      run: ./gradlew modrinth
      env:
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
