
name: modrinth_publish

on:
  workflow_dispatch:

jobs:
  modrinth_publish:
    uses: ./.github/workflows/shared_build.yml
    steps:
    - name: Publish to Modrinth
      run: ./gradlew modrinth
      env:
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
