
name: modrinth_publish

on:
  workflow_dispatch:

jobs:
  modrinth_publish:
    steps:
      uses: ./.github/workflows/shared_build.yml
    - name: Publish to Modrinth
      run: ./gradlew modrinth
      env:
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
