
name: modrinth_publish

on:
  workflow_dispatch:

jobs:
  modrinth_publish:
    runs-on: ubuntu-latest
    steps:
      uses: ./.github/actions/shared_build
    - name: Publish to Modrinth
      run: ./gradlew modrinth
      env:
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
